let ent = [
    {
       title: 'LEFT ARROW',
       name1: 'UNICODE', code1: 'U+02190',
       name2: 'HEX CODE', code2: '&#x2190;',
       name3: 'HTML CODE', code3: '&#8592;', h1: '&#8592;',
       name4: 'HTML ENTITY', code4: '&larr;',
    },
    {
       title: 'UP ARROW',
       name1: 'UNICODE', code1: 'U+02191',
       name2: 'HEX CODE', code2: '&#x2191;',
       name3: 'HTML CODE', code3: '&#8593;', h1: '&#8593;',
       name4: 'HTML ENTITY', code4: '&uarr;',
    },
    {
       title: 'RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+02192',
       name2: 'HEX CODE', code2: '&#x2192;',
       name3: 'HTML CODE', code3: '&#8594;', h1: '&#8594;',
       name4: 'HTML ENTITY', code4: '&rarr;',
    },
    {
       title: 'DOWN ARROW',
       name1: 'UNICODE', code1: 'U+02193',
       name2: 'HEX CODE', code2: '&#x2193;',
       name3: 'HTML CODE', code3: '&#8595;', h1: '&#8595;',
       name4: 'HTML ENTITY', code4: '&darr;',
    },
    {
       title: 'LEFT RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+02194',
       name2: 'HEX CODE', code2: '&#x2194;',
       name3: 'HTML CODE', code3: '&#8596;', h1: '&#8596;',
       name4: 'HTML ENTITY', code4: '&harr;',
    },
    {
       title: 'UP DOWN ARROW',
       name1: 'UNICODE', code1: 'U+02195',
       name2: 'HEX CODE', code2: '&#x2195;',
       name3: 'HTML CODE', code3: '&#8597;', h1: '&#8597;',
       name4: 'HTML ENTITY', code4: '&varr;',
    },
    {
       title: 'NORTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+02196',
       name2: 'HEX CODE', code2: '&#x2196;',
       name3: 'HTML CODE', code3: '&#8598;', h1: '&#8598;',
       name4: 'HTML ENTITY', code4: '&nwarr;',
    },
    {
       title: 'NORTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02197',
       name2: 'HEX CODE', code2: '&#x2197;',
       name3: 'HTML CODE', code3: '&#8599;', h1: '&#8599;',
       name4: 'HTML ENTITY', code4: '&nearr;',
    },
    {
       title: 'SOUTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02198',
       name2: 'HEX CODE', code2: '&#x2198;',
       name3: 'HTML CODE', code3: '&#8600;', h1: '&#8600;',
       name4: 'HTML ENTITY', code4: '&searr;',
    },
    {
       title: 'SOUTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+02199',
       name2: 'HEX CODE', code2: '&#x2199;',
       name3: 'HTML CODE', code3: '&#8601;', h1: '&#8601;',
       name4: 'HTML ENTITY', code4: '&swarr;',
    },
    {
       title: 'LEFT ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+0219A',
       name2: 'HEX CODE', code2: '&#x219a;',
       name3: 'HTML CODE', code3: '&#8602;', h1: '&#8602;',
       name4: 'HTML ENTITY', code4: '&nlarr;',
    },
    {
       title: 'RIGHT ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+0219B',
       name2: 'HEX CODE', code2: '&#x219b;',
       name3: 'HTML CODE', code3: '&#8603;', h1: '&#8603;',
       name4: 'HTML ENTITY', code4: '&nrarr;',
    },
    {
       title: 'LEFT WAVE ARROW',
       name1: 'UNICODE', code1: 'U+0219C',
       name2: 'HEX CODE', code2: '&#x219c;',
       name3: 'HTML CODE', code3: '&#8604;', h1: '&#8604;',
       name4: 'HTML ENTITY', code4: '&larrw;',
    },
    {
       title: 'RIGHT WAVE ARROW',
       name1: 'UNICODE', code1: 'U+0219D',
       name2: 'HEX CODE', code2: '&#x219d;',
       name3: 'HTML CODE', code3: '&#8605;', h1: '&#8605;',
       name4: 'HTML ENTITY', code4: '&rarrw;',
    },
    {
       title: 'LEFT TWO HEADED ARROW',
       name1: 'UNICODE', code1: 'U+0219E',
       name2: 'HEX CODE', code2: '&#x219e;',
       name3: 'HTML CODE', code3: '&#8606;', h1: '&#8606;',
       name4: 'HTML ENTITY', code4: '&Larr;',
    },
    {
       title: 'UP TWO HEADED ARROW',
       name1: 'UNICODE', code1: 'U+0219F',
       name2: 'HEX CODE', code2: '&#x219f;',
       name3: 'HTML CODE', code3: '&#8607;', h1: '&#8607;',
       name4: 'HTML ENTITY', code4: '&Uarr;',
    },
    {
       title: 'RIGHT TWO HEADED ARROW',
       name1: 'UNICODE', code1: 'U+021A0',
       name2: 'HEX CODE', code2: '&#x21a0;',
       name3: 'HTML CODE', code3: '&#8608;', h1: '&#8608;',
       name4: 'HTML ENTITY', code4: '&Rarr;',
    },
    {
       title: 'DOWN TWO HEADED ARROW',
       name1: 'UNICODE', code1: 'U+021A1',
       name2: 'HEX CODE', code2: '&#x21a1;',
       name3: 'HTML CODE', code3: '&#8609;', h1: '&#8609;',
       name4: 'HTML ENTITY', code4: '&Darr;',
    },
    {
       title: 'LEFT ARROW WITH TAIL',
       name1: 'UNICODE', code1: 'U+021A2',
       name2: 'HEX CODE', code2: '&#x21a2;',
       name3: 'HTML CODE', code3: '&#8610;', h1: '&#8610;',
       name4: 'HTML ENTITY', code4: '&larrtl;',
    },
    {
       title: 'RIGHT ARROW WITH TAIL',
       name1: 'UNICODE', code1: 'U+021A3',
       name2: 'HEX CODE', code2: '&#x21a3;',
       name3: 'HTML CODE', code3: '&#8611;', h1: '&#8611;',
       name4: 'HTML ENTITY', code4: '&rarrtl;',
    },
    {
       title: 'LEFT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+021A4',
       name2: 'HEX CODE', code2: '&#x21a4;',
       name3: 'HTML CODE', code3: '&#8612;', h1: '&#8612;',
       name4: 'HTML ENTITY', code4: '&mapstoleft;',
    },
    {
       title: 'UP ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+021A5',
       name2: 'HEX CODE', code2: '&#x21a5;',
       name3: 'HTML CODE', code3: '&#8613;', h1: '&#8613;',
       name4: 'HTML ENTITY', code4: '&mapstoup;',
    },
    {
       title: 'RIGHT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+021A6',
       name2: 'HEX CODE', code2: '&#x21a6;',
       name3: 'HTML CODE', code3: '&#8614;', h1: '&#8614;',
       name4: 'HTML ENTITY', code4: '&mapstoright;',
    },
    {
       title: 'DOWN ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+021A7',
       name2: 'HEX CODE', code2: '&#x21a7;',
       name3: 'HTML CODE', code3: '&#8615;', h1: '&#8615;',
       name4: 'HTML ENTITY', code4: '&mapstodown;',
    },
    {
       title: 'UP DOWN ARROW WITH BASE',
       name1: 'UNICODE', code1: 'U+021A8',
       name2: 'HEX CODE', code2: '&#x21a8;',
       name3: 'HTML CODE', code3: '&#8616;', h1: '&#8616;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+021A9',
       name2: 'HEX CODE', code2: '&#x21a9;',
       name3: 'HTML CODE', code3: '&#8617;', h1: '&#8617;',
       name4: 'HTML ENTITY', code4: '&larrhk;',
    },
    {
       title: 'RIGHT ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+021AA',
       name2: 'HEX CODE', code2: '&#x21aa;',
       name3: 'HTML CODE', code3: '&#8618;', h1: '&#8618;',
       name4: 'HTML ENTITY', code4: '&rarrhk;',
    },
    {
       title: 'LEFT ARROW WITH LOOP',
       name1: 'UNICODE', code1: 'U+021AB',
       name2: 'HEX CODE', code2: '&#x21ab;',
       name3: 'HTML CODE', code3: '&#8619;', h1: '&#8619;',
       name4: 'HTML ENTITY', code4: '&larrlp;',
    },
    {
       title: 'RIGHT ARROW WITH LOOP',
       name1: 'UNICODE', code1: 'U+021AC',
       name2: 'HEX CODE', code2: '&#x21ac;',
       name3: 'HTML CODE', code3: '&#8620;', h1: '&#8620;',
       name4: 'HTML ENTITY', code4: '&rarrlp;',
    },
    {
       title: 'LEFT RIGHT WAVE ARROW',
       name1: 'UNICODE', code1: 'U+021AD',
       name2: 'HEX CODE', code2: '&#x21ad;',
       name3: 'HTML CODE', code3: '&#8621;', h1: '&#8621;',
       name4: 'HTML ENTITY', code4: '&harrw;',
    },
    {
       title: 'LEFT RIGHT ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+021AE',
       name2: 'HEX CODE', code2: '&#x21ae;',
       name3: 'HTML CODE', code3: '&#8622;', h1: '&#8622;',
       name4: 'HTML ENTITY', code4: '&nharr;',
    },
    {
       title: 'DOWN ZIGZAG ARROW',
       name1: 'UNICODE', code1: 'U+021AF',
       name2: 'HEX CODE', code2: '&#x21af;',
       name3: 'HTML CODE', code3: '&#8623;', h1: '&#8623;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP ARROW WITH TIP LEFT',
       name1: 'UNICODE', code1: 'U+021B0',
       name2: 'HEX CODE', code2: '&#x21b0;',
       name3: 'HTML CODE', code3: '&#8624;', h1: '&#8624;',
       name4: 'HTML ENTITY', code4: '&lsh;',
    },
    {
       title: 'UP ARROW WITH TIP RIGHT',
       name1: 'UNICODE', code1: 'U+021B1',
       name2: 'HEX CODE', code2: '&#x21b1;',
       name3: 'HTML CODE', code3: '&#8625;', h1: '&#8625;',
       name4: 'HTML ENTITY', code4: '&rsh;',
    },
    {
       title: 'DOWN ARROW WITH TIP LEFT',
       name1: 'UNICODE', code1: 'U+021B2',
       name2: 'HEX CODE', code2: '&#x21b2;',
       name3: 'HTML CODE', code3: '&#8626;', h1: '&#8626;',
       name4: 'HTML ENTITY', code4: '&ldsh;',
    },
    {
       title: 'DOWN ARROW WITH TIP RIGHT',
       name1: 'UNICODE', code1: 'U+021B3',
       name2: 'HEX CODE', code2: '&#x21b3;',
       name3: 'HTML CODE', code3: '&#8627;', h1: '&#8627;',
       name4: 'HTML ENTITY', code4: '&rdsh;',
    },
    {
       title: 'RIGHT ARROW WITH CORNER DOWN',
       name1: 'UNICODE', code1: 'U+021B4',
       name2: 'HEX CODE', code2: '&#x21b4;',
       name3: 'HTML CODE', code3: '&#8628;', h1: '&#8628;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN ARROW WITH CORNER LEFT',
       name1: 'UNICODE', code1: 'U+021B5',
       name2: 'HEX CODE', code2: '&#x21b5;',
       name3: 'HTML CODE', code3: '&#8629;', h1: '&#8629;',
       name4: 'HTML ENTITY', code4: '&crarr;',
    },
    {
       title: 'ANTICLOCKWISE TOP SEMICIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+021B6',
       name2: 'HEX CODE', code2: '&#x21b6;',
       name3: 'HTML CODE', code3: '&#8630;', h1: '&#8630;',
       name4: 'HTML ENTITY', code4: '&cularr;',
    },
    {
       title: 'CLOCKWISE TOP SEMICIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+021B7',
       name2: 'HEX CODE', code2: '&#x21b7;',
       name3: 'HTML CODE', code3: '&#8631;', h1: '&#8631;',
       name4: 'HTML ENTITY', code4: '&curarr;',
    },
    {
       title: 'NORTH WEST ARROW TO LONG BAR',
       name1: 'UNICODE', code1: 'U+021B8',
       name2: 'HEX CODE', code2: '&#x21b8;',
       name3: 'HTML CODE', code3: '&#8632;', h1: '&#8632;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW TO BAR OVER RIGHT ARROW TO BAR',
       name1: 'UNICODE', code1: 'U+021B9',
       name2: 'HEX CODE', code2: '&#x21b9;',
       name3: 'HTML CODE', code3: '&#8633;', h1: '&#8633;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'ANTICLOCKWISE OPEN CIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+021BA',
       name2: 'HEX CODE', code2: '&#x21ba;',
       name3: 'HTML CODE', code3: '&#8634;', h1: '&#8634;',
       name4: 'HTML ENTITY', code4: '&olarr;',
    },
    {
       title: 'CLOCKWISE OPEN CIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+021BB',
       name2: 'HEX CODE', code2: '&#x21bb;',
       name3: 'HTML CODE', code3: '&#8635;', h1: '&#8635;',
       name4: 'HTML ENTITY', code4: '&orarr;',
    },
    {
       title: 'LEFT HARPOON WITH BARB UP',
       name1: 'UNICODE', code1: 'U+021BC',
       name2: 'HEX CODE', code2: '&#x21bc;',
       name3: 'HTML CODE', code3: '&#8636;', h1: '&#8636;',
       name4: 'HTML ENTITY', code4: '&lharu;',
    },
    {
       title: 'LEFT HARPOON WITH BARB DOWN',
       name1: 'UNICODE', code1: 'U+021BD',
       name2: 'HEX CODE', code2: '&#x21bd;',
       name3: 'HTML CODE', code3: '&#8637;', h1: '&#8637;',
       name4: 'HTML ENTITY', code4: '&lhard;',
    },
    {
       title: 'UP HARPOON WITH BARB RIGHT',
       name1: 'UNICODE', code1: 'U+021BE',
       name2: 'HEX CODE', code2: '&#x21be;',
       name3: 'HTML CODE', code3: '&#8638;', h1: '&#8638;',
       name4: 'HTML ENTITY', code4: '&uharr;',
    },
    {
       title: 'UP HARPOON WITH BARB LEFT',
       name1: 'UNICODE', code1: 'U+021BF',
       name2: 'HEX CODE', code2: '&#x21bf;',
       name3: 'HTML CODE', code3: '&#8639;', h1: '&#8639;',
       name4: 'HTML ENTITY', code4: '&uharl;',
    },
    {
       title: 'RIGHT HARPOON WITH BARB UP',
       name1: 'UNICODE', code1: 'U+021C0',
       name2: 'HEX CODE', code2: '&#x21c0;',
       name3: 'HTML CODE', code3: '&#8640;', h1: '&#8640;',
       name4: 'HTML ENTITY', code4: '&rharu;',
    },
    {
       title: 'RIGHT HARPOON WITH BARB DOWN',
       name1: 'UNICODE', code1: 'U+021C1',
       name2: 'HEX CODE', code2: '&#x21c1;',
       name3: 'HTML CODE', code3: '&#8641;', h1: '&#8641;',
       name4: 'HTML ENTITY', code4: '&rhard;',
    },
    {
       title: 'DOWN HARPOON WITH BARB RIGHT',
       name1: 'UNICODE', code1: 'U+021C2',
       name2: 'HEX CODE', code2: '&#x21c2;',
       name3: 'HTML CODE', code3: '&#8642;', h1: '&#8642;',
       name4: 'HTML ENTITY', code4: '&dharr;',
    },
    {
       title: 'DOWN HARPOON WITH BARB LEFT',
       name1: 'UNICODE', code1: 'U+021C3',
       name2: 'HEX CODE', code2: '&#x21c3;',
       name3: 'HTML CODE', code3: '&#8643;', h1: '&#8643;',
       name4: 'HTML ENTITY', code4: '&dharl;',
    },
    {
       title: 'RIGHT ARROW OVER LEFT ARROW',
       name1: 'UNICODE', code1: 'U+021C4',
       name2: 'HEX CODE', code2: '&#x21c4;',
       name3: 'HTML CODE', code3: '&#8644;', h1: '&#8644;',
       name4: 'HTML ENTITY', code4: '&rlarr;',
    },
    {
       title: 'UP ARROW LEFT OF DOWN ARROW',
       name1: 'UNICODE', code1: 'U+021C5',
       name2: 'HEX CODE', code2: '&#x21c5;',
       name3: 'HTML CODE', code3: '&#8645;', h1: '&#8645;',
       name4: 'HTML ENTITY', code4: '&udarr;',
    },
    {
       title: 'LEFT ARROW OVER RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+021C6',
       name2: 'HEX CODE', code2: '&#x21c6;',
       name3: 'HTML CODE', code3: '&#8646;', h1: '&#8646;',
       name4: 'HTML ENTITY', code4: '&lrarr;',
    },
    {
       title: 'LEFT PAIRED ARROWS',
       name1: 'UNICODE', code1: 'U+021C7',
       name2: 'HEX CODE', code2: '&#x21c7;',
       name3: 'HTML CODE', code3: '&#8647;', h1: '&#8647;',
       name4: 'HTML ENTITY', code4: '&llarr;',
    },
    {
       title: 'UP PAIRED ARROWS',
       name1: 'UNICODE', code1: 'U+021C8',
       name2: 'HEX CODE', code2: '&#x21c8;',
       name3: 'HTML CODE', code3: '&#8648;', h1: '&#8648;',
       name4: 'HTML ENTITY', code4: '&uuarr;',
    },
    {
       title: 'RIGHT PAIRED ARROWS',
       name1: 'UNICODE', code1: 'U+021C9',
       name2: 'HEX CODE', code2: '&#x21c9;',
       name3: 'HTML CODE', code3: '&#8649;', h1: '&#8649;',
       name4: 'HTML ENTITY', code4: '&rrarr;',
    },
    {
       title: 'DOWNARDS PAIRED ARROWS',
       name1: 'UNICODE', code1: 'U+021CA',
       name2: 'HEX CODE', code2: '&#x21cA;',
       name3: 'HTML CODE', code3: '&#8650;', h1: '&#8650;',
       name4: 'HTML ENTITY', code4: '&ddarr;',
    },
    {
       title: 'LEFT HARPOON OVER RIGHT HARPOON',
       name1: 'UNICODE', code1: 'U+021CB',
       name2: 'HEX CODE', code2: '&#x21cb;',
       name3: 'HTML CODE', code3: '&#8651;', h1: '&#8651;',
       name4: 'HTML ENTITY', code4: '&lrhar;',
    },
    {
       title: 'RIGHT HARPOON OVER LEFT HARPOON',
       name1: 'UNICODE', code1: 'U+021CC',
       name2: 'HEX CODE', code2: '&#x21cc;',
       name3: 'HTML CODE', code3: '&#8652;', h1: '&#8652;',
       name4: 'HTML ENTITY', code4: '&rlhar;',
    },
    {
       title: 'LEFT DOUBLE ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+021CD',
       name2: 'HEX CODE', code2: '&#x21cd;',
       name3: 'HTML CODE', code3: '&#8653;', h1: '&#8653;',
       name4: 'HTML ENTITY', code4: '&nlArr;',
    },
    {
       title: 'LEFT RIGHT DOUBLE ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+021CE',
       name2: 'HEX CODE', code2: '&#x21ce;',
       name3: 'HTML CODE', code3: '&#8654;', h1: '&#8654;',
       name4: 'HTML ENTITY', code4: '&nhArr;',
    },
    {
       title: 'RIGHT DOUBLE ARROW WITH STROKE',
       name1: 'UNICODE', code1: 'U+021CF',
       name2: 'HEX CODE', code2: '&#x21cf;',
       name3: 'HTML CODE', code3: '&#8655;', h1: '&#8655;',
       name4: 'HTML ENTITY', code4: '&nrArr;',
    },
    {
       title: 'LEFT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D0',
       name2: 'HEX CODE', code2: '&#x21d0;',
       name3: 'HTML CODE', code3: '&#8656;', h1: '&#8656;',
       name4: 'HTML ENTITY', code4: '&lArr;',
    },
    {
       title: 'UP DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D1',
       name2: 'HEX CODE', code2: '&#x21d1;',
       name3: 'HTML CODE', code3: '&#8657;', h1: '&#8657;',
       name4: 'HTML ENTITY', code4: '&uArr;',
    },
    {
       title: 'RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D2',
       name2: 'HEX CODE', code2: '&#x21d2;',
       name3: 'HTML CODE', code3: '&#8658;', h1: '&#8658;',
       name4: 'HTML ENTITY', code4: '&rArr;',
    },
    {
       title: 'DOWN DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D3',
       name2: 'HEX CODE', code2: '&#x21d3;',
       name3: 'HTML CODE', code3: '&#8659;', h1: '&#8659;',
       name4: 'HTML ENTITY', code4: '&dArr;',
    },
    {
       title: 'LEFT RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D4',
       name2: 'HEX CODE', code2: '&#x21d4;',
       name3: 'HTML CODE', code3: '&#8660;', h1: '&#8660;',
       name4: 'HTML ENTITY', code4: '&hArr;',
    },
    {
       title: 'UP DOWN DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D5',
       name2: 'HEX CODE', code2: '&#x21d5;',
       name3: 'HTML CODE', code3: '&#8661;', h1: '&#8661;',
       name4: 'HTML ENTITY', code4: '&vArr;',
    },
    {
       title: 'NORTH WEST DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D6',
       name2: 'HEX CODE', code2: '&#x21d6;',
       name3: 'HTML CODE', code3: '&#8662;', h1: '&#8662;',
       name4: 'HTML ENTITY', code4: '&nwArr;',
    },
    {
       title: 'NORTH EAST DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D7',
       name2: 'HEX CODE', code2: '&#x21d7;',
       name3: 'HTML CODE', code3: '&#8663;', h1: '&#8663;',
       name4: 'HTML ENTITY', code4: '&neArr;',
    },
    {
       title: 'SOUTH EAST DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D8',
       name2: 'HEX CODE', code2: '&#x21d8;',
       name3: 'HTML CODE', code3: '&#8664;', h1: '&#8664;',
       name4: 'HTML ENTITY', code4: '&seArr;',
    },
    {
       title: 'SOUTH WEST DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021D9',
       name2: 'HEX CODE', code2: '&#x21d9;',
       name3: 'HTML CODE', code3: '&#8665;', h1: '&#8665;',
       name4: 'HTML ENTITY', code4: '&swArr;',
    },
    {
       title: 'LEFT TRIPLE ARROW',
       name1: 'UNICODE', code1: 'U+021DA',
       name2: 'HEX CODE', code2: '&#x21da;',
       name3: 'HTML CODE', code3: '&#8666;', h1: '&#8666;',
       name4: 'HTML ENTITY', code4: '&lAarr;',
    },
    {
       title: 'RIGHT TRIPLE ARROW',
       name1: 'UNICODE', code1: 'U+021DB',
       name2: 'HEX CODE', code2: '&#x21db;',
       name3: 'HTML CODE', code3: '&#8667;', h1: '&#8667;',
       name4: 'HTML ENTITY', code4: '&rAarr;',
    },
    {
       title: 'LEFT SQUIGGLE ARROW',
       name1: 'UNICODE', code1: 'U+021DC',
       name2: 'HEX CODE', code2: '&#x21dc;',
       name3: 'HTML CODE', code3: '&#8668;', h1: '&#8668;',
       name4: 'HTML ENTITY', code4: '&ziglarr;',
    },
    {
       title: 'RIGHT SQUIGGLE ARROW',
       name1: 'UNICODE', code1: 'U+021DD',
       name2: 'HEX CODE', code2: '&#x21dd;',
       name3: 'HTML CODE', code3: '&#8669;', h1: '&#8669;',
       name4: 'HTML ENTITY', code4: '&zigrarr;',
    },
    {
       title: 'UP ARROW WITH DOUBLE STROKE',
       name1: 'UNICODE', code1: 'U+021DE',
       name2: 'HEX CODE', code2: '&#x21de;',
       name3: 'HTML CODE', code3: '&#8670;', h1: '&#8670;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN ARROW WITH DOUBLE STROKE',
       name1: 'UNICODE', code1: 'U+021DF',
       name2: 'HEX CODE', code2: '&#x21df;',
       name3: 'HTML CODE', code3: '&#8671;', h1: '&#8671;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT DASHED ARROW',
       name1: 'UNICODE', code1: 'U+021E0',
       name2: 'HEX CODE', code2: '&#x21e0;',
       name3: 'HTML CODE', code3: '&#8672;', h1: '&#8672;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP DASHED ARROW',
       name1: 'UNICODE', code1: 'U+021E1',
       name2: 'HEX CODE', code2: '&#x21e1;',
       name3: 'HTML CODE', code3: '&#8673;', h1: '&#8673;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT DASHED ARROW',
       name1: 'UNICODE', code1: 'U+021E2',
       name2: 'HEX CODE', code2: '&#x21e2;',
       name3: 'HTML CODE', code3: '&#8674;', h1: '&#8674;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN DASHED ARROW',
       name1: 'UNICODE', code1: 'U+021E3',
       name2: 'HEX CODE', code2: '&#x21e3;',
       name3: 'HTML CODE', code3: '&#8675;', h1: '&#8675;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW TO BAR',
       name1: 'UNICODE', code1: 'U+021E4',
       name2: 'HEX CODE', code2: '&#x21e4;',
       name3: 'HTML CODE', code3: '&#8676;', h1: '&#8676;',
       name4: 'HTML ENTITY', code4: '&larrb;',
    },
    {
       title: 'RIGHT ARROW TO BAR',
       name1: 'UNICODE', code1: 'U+021E5',
       name2: 'HEX CODE', code2: '&#x21e5;',
       name3: 'HTML CODE', code3: '&#8677;', h1: '&#8677;',
       name4: 'HTML ENTITY', code4: '&rarrb;',
    },
    {
       title: 'LEFT WHITE ARROW',
       name1: 'UNICODE', code1: 'U+021E6',
       name2: 'HEX CODE', code2: '&#x21e6;',
       name3: 'HTML CODE', code3: '&#8678;', h1: '&#8678;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE ARROW',
       name1: 'UNICODE', code1: 'U+021E7',
       name2: 'HEX CODE', code2: '&#x21e7;',
       name3: 'HTML CODE', code3: '&#8679;', h1: '&#8679;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT WHITE ARROW',
       name1: 'UNICODE', code1: 'U+021E8',
       name2: 'HEX CODE', code2: '&#x21e8;',
       name3: 'HTML CODE', code3: '&#8680;', h1: '&#8680;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN WHITE ARROW',
       name1: 'UNICODE', code1: 'U+021E9',
       name2: 'HEX CODE', code2: '&#x21e9;',
       name3: 'HTML CODE', code3: '&#8681;', h1: '&#8681;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+021EA',
       name2: 'HEX CODE', code2: '&#x21ea;',
       name3: 'HTML CODE', code3: '&#8682;', h1: '&#8682;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE ARROW ON PEDESTAL',
       name1: 'UNICODE', code1: 'U+021EB',
       name2: 'HEX CODE', code2: '&#x21eb;',
       name3: 'HTML CODE', code3: '&#8683;', h1: '&#8683;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE ARROW ON PEDESTAL WITH HORIZONTAL BAR',
       name1: 'UNICODE', code1: 'U+021EC',
       name2: 'HEX CODE', code2: '&#x21ec;',
       name3: 'HTML CODE', code3: '&#8684;', h1: '&#8684;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE ARROW ON PEDESTAL WITH VERTICAL BAR',
       name1: 'UNICODE', code1: 'U+021ED',
       name2: 'HEX CODE', code2: '&#x21ed;',
       name3: 'HTML CODE', code3: '&#8685;', h1: '&#8685;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+021EE',
       name2: 'HEX CODE', code2: '&#x21ee;',
       name3: 'HTML CODE', code3: '&#8686;', h1: '&#8686;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP WHITE DOUBLE ARROW ON PEDESTAL',
       name1: 'UNICODE', code1: 'U+021EF',
       name2: 'HEX CODE', code2: '&#x21ef;',
       name3: 'HTML CODE', code3: '&#8687;', h1: '&#8687;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT WHITE ARROW FROM WALL',
       name1: 'UNICODE', code1: 'U+021F0',
       name2: 'HEX CODE', code2: '&#x21f0;',
       name3: 'HTML CODE', code3: '&#8688;', h1: '&#8688;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'NORTH WEST ARROW TO CORNER',
       name1: 'UNICODE', code1: 'U+021F1',
       name2: 'HEX CODE', code2: '&#x21f1;',
       name3: 'HTML CODE', code3: '&#8689;', h1: '&#8689;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'SOUTH EAST ARROW TO CORNER',
       name1: 'UNICODE', code1: 'U+021F2',
       name2: 'HEX CODE', code2: '&#x21f2;',
       name3: 'HTML CODE', code3: '&#8690;', h1: '&#8690;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP DOWN WHITE ARROW',
       name1: 'UNICODE', code1: 'U+021F3',
       name2: 'HEX CODE', code2: '&#x21f3;',
       name3: 'HTML CODE', code3: '&#8691;', h1: '&#8691;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT ARROW WITH SMALL CIRCLE',
       name1: 'UNICODE', code1: 'U+021F4',
       name2: 'HEX CODE', code2: '&#x21f4;',
       name3: 'HTML CODE', code3: '&#8692;', h1: '&#8692;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN ARROW LEFT OF UP ARROW',
       name1: 'UNICODE', code1: 'U+021F5',
       name2: 'HEX CODE', code2: '&#x21f5;',
       name3: 'HTML CODE', code3: '&#8693;', h1: '&#8693;',
       name4: 'HTML ENTITY', code4: '&duarr;',
    },
    {
       title: 'THREE RIGHT ARROWS',
       name1: 'UNICODE', code1: 'U+021F6',
       name2: 'HEX CODE', code2: '&#x21f6;',
       name3: 'HTML CODE', code3: '&#8694;', h1: '&#8694;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021F7',
       name2: 'HEX CODE', code2: '&#x21f7;',
       name3: 'HTML CODE', code3: '&#8695;', h1: '&#8695;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021F8',
       name2: 'HEX CODE', code2: '&#x21f8;',
       name3: 'HTML CODE', code3: '&#8696;', h1: '&#8696;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT RIGHT ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021F9',
       name2: 'HEX CODE', code2: '&#x21f9;',
       name3: 'HTML CODE', code3: '&#8697;', h1: '&#8697;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021FA',
       name2: 'HEX CODE', code2: '&#x21fa;',
       name3: 'HTML CODE', code3: '&#8698;', h1: '&#8698;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT ARROW WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021FB',
       name2: 'HEX CODE', code2: '&#x21fb;',
       name3: 'HTML CODE', code3: '&#8699;', h1: '&#8699;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT RIGHT ARROW WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+021FC',
       name2: 'HEX CODE', code2: '&#x21fc;',
       name3: 'HTML CODE', code3: '&#8700;', h1: '&#8700;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT OPEN-HEADED ARROW',
       name1: 'UNICODE', code1: 'U+021FD',
       name2: 'HEX CODE', code2: '&#x21fd;',
       name3: 'HTML CODE', code3: '&#8701;', h1: '&#8701;',
       name4: 'HTML ENTITY', code4: '&loarr;',
    },
    {
       title: 'RIGHT OPEN-HEADED ARROW',
       name1: 'UNICODE', code1: 'U+021FE',
       name2: 'HEX CODE', code2: '&#x21fe;',
       name3: 'HTML CODE', code3: '&#8702;', h1: '&#8702;',
       name4: 'HTML ENTITY', code4: '&roarr;',
    },
    {
       title: 'LEFT RIGHT OPEN-HEADED ARROW',
       name1: 'UNICODE', code1: 'U+021FF',
       name2: 'HEX CODE', code2: '&#x21ff;',
       name3: 'HTML CODE', code3: '&#8703;', h1: '&#8703;',
       name4: 'HTML ENTITY', code4: '&hoarr;',
    },
    {
       title: 'UP QUADRUPLE ARROW',
       name1: 'UNICODE', code1: 'U+027F0',
       name2: 'HEX CODE', code2: '&#x27F0;',
       name3: 'HTML CODE', code3: '&#10224;', h1: '&#10224;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN QUADRUPLE ARROW',
       name1: 'UNICODE', code1: 'U+027F1',
       name2: 'HEX CODE', code2: '&#x27F1;',
       name3: 'HTML CODE', code3: '&#10225;', h1: '&#10225;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'ANTICLOCKWISE GAPPED CIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+027F2',
       name2: 'HEX CODE', code2: '&#x27F2;',
       name3: 'HTML CODE', code3: '&#10226;', h1: '&#10226;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'CLOCKWISE GAPPED CIRCLE ARROW',
       name1: 'UNICODE', code1: 'U+027F3',
       name2: 'HEX CODE', code2: '&#x27F3;',
       name3: 'HTML CODE', code3: '&#10227;', h1: '&#10227;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT ARROW WITH CIRCLED PLUS',
       name1: 'UNICODE', code1: 'U+027F4',
       name2: 'HEX CODE', code2: '&#x27F4;',
       name3: 'HTML CODE', code3: '&#10228;', h1: '&#10228;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LONG LEFT ARROW',
       name1: 'UNICODE', code1: 'U+027F5',
       name2: 'HEX CODE', code2: '&#x27F5;',
       name3: 'HTML CODE', code3: '&#10229;', h1: '&#10229;',
       name4: 'HTML ENTITY', code4: '&xlarr;',
    },
    {
       title: 'LONG RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+027F6',
       name2: 'HEX CODE', code2: '&#x27F6;',
       name3: 'HTML CODE', code3: '&#10230;', h1: '&#10230;',
       name4: 'HTML ENTITY', code4: '&xrarr;',
    },
    {
       title: 'LONG LEFT RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+027F7',
       name2: 'HEX CODE', code2: '&#x27F7;',
       name3: 'HTML CODE', code3: '&#10231;', h1: '&#10231;',
       name4: 'HTML ENTITY', code4: '&xharr;',
    },
    {
       title: 'LONG LEFT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027F8',
       name2: 'HEX CODE', code2: '&#x27F8;',
       name3: 'HTML CODE', code3: '&#10232;', h1: '&#10232;',
       name4: 'HTML ENTITY', code4: '&xlArr;',
    },
    {
       title: 'LONG RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027F9',
       name2: 'HEX CODE', code2: '&#x27F9;',
       name3: 'HTML CODE', code3: '&#10233;', h1: '&#10233;',
       name4: 'HTML ENTITY', code4: '&xrArr;',
    },
    {
       title: 'LONG LEFT RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027FA',
       name2: 'HEX CODE', code2: '&#x27FA;',
       name3: 'HTML CODE', code3: '&#10234;', h1: '&#10234;',
       name4: 'HTML ENTITY', code4: '&xhArr;',
    },
    {
       title: 'LONG LEFT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FB',
       name2: 'HEX CODE', code2: '&#x27FB;',
       name3: 'HTML CODE', code3: '&#10235;', h1: '&#10235;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LONG RIGHT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FC',
       name2: 'HEX CODE', code2: '&#x27FC;',
       name3: 'HTML CODE', code3: '&#10236;', h1: '&#10236;',
       name4: 'HTML ENTITY', code4: '&xmap;',
    },
    {
       title: 'LONG LEFT RIGHT ARROW',
       name1: 'UNICODE', code1: 'U+027F7',
       name2: 'HEX CODE', code2: '&#x27F7;',
       name3: 'HTML CODE', code3: '&#10231;', h1: '&#10231;',
       name4: 'HTML ENTITY', code4: '&xharr;',
    },
    {
       title: 'LONG LEFT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027F8',
       name2: 'HEX CODE', code2: '&#x27F8;',
       name3: 'HTML CODE', code3: '&#10232;', h1: '&#10232;',
       name4: 'HTML ENTITY', code4: '&xlArr;',
    },
    {
       title: 'LONG RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027F9',
       name2: 'HEX CODE', code2: '&#x27F9;',
       name3: 'HTML CODE', code3: '&#10233;', h1: '&#10233;',
       name4: 'HTML ENTITY', code4: '&xrArr;',
    },
    {
       title: 'LONG LEFT RIGHT DOUBLE ARROW',
       name1: 'UNICODE', code1: 'U+027FA',
       name2: 'HEX CODE', code2: '&#x27FA;',
       name3: 'HTML CODE', code3: '&#10234;', h1: '&#10234;',
       name4: 'HTML ENTITY', code4: '&xhArr;',
    },
    {
       title: 'LONG LEFT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FB',
       name2: 'HEX CODE', code2: '&#x27FB;',
       name3: 'HTML CODE', code3: '&#10235;', h1: '&#10235;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LONG RIGHT ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FC',
       name2: 'HEX CODE', code2: '&#x27FC;',
       name3: 'HTML CODE', code3: '&#10236;', h1: '&#10236;',
       name4: 'HTML ENTITY', code4: '&xmap;',
    },
    {
       title: 'LONG LEFT DOUBLE ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FD',
       name2: 'HEX CODE', code2: '&#x27FD;',
       name3: 'HTML CODE', code3: '&#10237;', h1: '&#10237;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LONG RIGHT DOUBLE ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+027FE',
       name2: 'HEX CODE', code2: '&#x27FE;',
       name3: 'HTML CODE', code3: '&#10238;', h1: '&#10238;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LONG RIGHT SQUIGGLE ARROW',
       name1: 'UNICODE', code1: 'U+027FF',
       name2: 'HEX CODE', code2: '&#x27FF;',
       name3: 'HTML CODE', code3: '&#10239;', h1: '&#10239;',
       name4: 'HTML ENTITY', code4: '&dzigrarr;',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02900',
       name2: 'HEX CODE', code2: '&#x2900;',
       name3: 'HTML CODE', code3: '&#10496;', h1: '&#10496;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02901',
       name2: 'HEX CODE', code2: '&#x2901;',
       name3: 'HTML CODE', code3: '&#10497;', h1: '&#10497;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT DOUBLE ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02902',
       name2: 'HEX CODE', code2: '&#x2902;',
       name3: 'HTML CODE', code3: '&#10498;', h1: '&#10498;',
       name4: 'HTML ENTITY', code4: '&nvlArr;',
    },
    {
       title: 'RIGHT DOUBLE ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02903',
       name2: 'HEX CODE', code2: '&#x2903;',
       name3: 'HTML CODE', code3: '&#10499;', h1: '&#10499;',
       name4: 'HTML ENTITY', code4: '&nvrArr;',
    },
    {
       title: 'LEFT RIGHT DOUBLE ARROW WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02904',
       name2: 'HEX CODE', code2: '&#x2904;',
       name3: 'HTML CODE', code3: '&#10500;', h1: '&#10500;',
       name4: 'HTML ENTITY', code4: '&nvHarr;',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+02905',
       name2: 'HEX CODE', code2: '&#x2905;',
       name3: 'HTML CODE', code3: '&#10501;', h1: '&#10501;',
       name4: 'HTML ENTITY', code4: '&Map;',
    },
    {
       title: 'LEFT DOUBLE ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+02906',
       name2: 'HEX CODE', code2: '&#x2906;',
       name3: 'HTML CODE', code3: '&#10502;', h1: '&#10502;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT DOUBLE ARROW FROM BAR',
       name1: 'UNICODE', code1: 'U+02907',
       name2: 'HEX CODE', code2: '&#x2907;',
       name3: 'HTML CODE', code3: '&#10503;', h1: '&#10503;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN ARROW WITH HORIZONTAL STROKE',
       name1: 'UNICODE', code1: 'U+02908',
       name2: 'HEX CODE', code2: '&#x2908;',
       name3: 'HTML CODE', code3: '&#10504;', h1: '&#10504;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP ARROW WITH HORIZONTAL STROKE',
       name1: 'UNICODE', code1: 'U+02909',
       name2: 'HEX CODE', code2: '&#x2909;',
       name3: 'HTML CODE', code3: '&#10505;', h1: '&#10505;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'UP TRIPLE ARROW',
       name1: 'UNICODE', code1: 'U+0290A',
       name2: 'HEX CODE', code2: '&#x290A;',
       name3: 'HTML CODE', code3: '&#10506;', h1: '&#10506;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'DOWN TRIPLE ARROW',
       name1: 'UNICODE', code1: 'U+0290B',
       name2: 'HEX CODE', code2: '&#x290B;',
       name3: 'HTML CODE', code3: '&#10507;', h1: '&#10507;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT DOUBLE DASH ARROW',
       name1: 'UNICODE', code1: 'U+0290C',
       name2: 'HEX CODE', code2: '&#x290C;',
       name3: 'HTML CODE', code3: '&#10508;', h1: '&#10508;',
       name4: 'HTML ENTITY', code4: '&lbarr;',
    },
    {
       title: 'RIGHT DOUBLE DASH ARROW',
       name1: 'UNICODE', code1: 'U+0290D',
       name2: 'HEX CODE', code2: '&#x290D;',
       name3: 'HTML CODE', code3: '&#10509;', h1: '&#10509;',
       name4: 'HTML ENTITY', code4: '&rbarr;',
    },
    {
       title: 'LEFT TRIPLE DASH ARROW',
       name1: 'UNICODE', code1: 'U+0290E',
       name2: 'HEX CODE', code2: '&#x290E;',
       name3: 'HTML CODE', code3: '&#10510;', h1: '&#10510;',
       name4: 'HTML ENTITY', code4: '&lBarr;',
    },
    {
       title: 'RIGHT TRIPLE DASH ARROW',
       name1: 'UNICODE', code1: 'U+0290F',
       name2: 'HEX CODE', code2: '&#x290F;',
       name3: 'HTML CODE', code3: '&#10511;', h1: '&#10511;',
       name4: 'HTML ENTITY', code4: '&rBarr;',
    },
    {
       title: 'RIGHT TWO-HEADED TRIPLE DASH ARROW',
       name1: 'UNICODE', code1: 'U+02910',
       name2: 'HEX CODE', code2: '&#x2910;',
       name3: 'HTML CODE', code3: '&#10512;', h1: '&#10512;',
       name4: 'HTML ENTITY', code4: '&RBarr;',
    },
    {
       title: 'RIGHT ARROW WITH DOTTED STEM',
       name1: 'UNICODE', code1: 'U+02911',
       name2: 'HEX CODE', code2: '&#x2911;',
       name3: 'HTML CODE', code3: '&#10513;', h1: '&#10513;',
       name4: 'HTML ENTITY', code4: '&DDotrahd;',
    },
    {
       title: 'UP ARROW TO BAR',
       name1: 'UNICODE', code1: 'U+02912',
       name2: 'HEX CODE', code2: '&#x2912;',
       name3: 'HTML CODE', code3: '&#10514;', h1: '&#10514;',
       name4: 'HTML ENTITY', code4: '&UpArrowBar;',
    },
    {
       title: 'DOWN ARROW TO BAR',
       name1: 'UNICODE', code1: 'U+02913',
       name2: 'HEX CODE', code2: '&#x2913;',
       name3: 'HTML CODE', code3: '&#10515;', h1: '&#10515;',
       name4: 'HTML ENTITY', code4: '&DownArrowBar;',
    },
    {
       title: 'RIGHT ARROW WITH TAIL WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02914',
       name2: 'HEX CODE', code2: '&#x2914;',
       name3: 'HTML CODE', code3: '&#10516;', h1: '&#10516;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02915',
       name2: 'HEX CODE', code2: '&#x2915;',
       name3: 'HTML CODE', code3: '&#10517;', h1: '&#10517;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW WITH TAIL',
       name1: 'UNICODE', code1: 'U+02916',
       name2: 'HEX CODE', code2: '&#x2916;',
       name3: 'HTML CODE', code3: '&#10518;', h1: '&#10518;',
       name4: 'HTML ENTITY', code4: '&Rarrtl;',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW WITH TAIL WITH VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02917',
       name2: 'HEX CODE', code2: '&#x2917;',
       name3: 'HTML CODE', code3: '&#10519;', h1: '&#10519;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RIGHT TWO-HEADED ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE',
       name1: 'UNICODE', code1: 'U+02918',
       name2: 'HEX CODE', code2: '&#x2918;',
       name3: 'HTML CODE', code3: '&#10520;', h1: '&#10520;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'LEFT ARROW-TAIL',
       name1: 'UNICODE', code1: 'U+02919',
       name2: 'HEX CODE', code2: '&#x2919;',
       name3: 'HTML CODE', code3: '&#10521;', h1: '&#10521;',
       name4: 'HTML ENTITY', code4: '&latail;',
    },
    {
       title: 'RIGHT ARROW-TAIL',
       name1: 'UNICODE', code1: 'U+0291A',
       name2: 'HEX CODE', code2: '&#x291A;',
       name3: 'HTML CODE', code3: '&#10522;', h1: '&#10522;',
       name4: 'HTML ENTITY', code4: '&ratail;',
    },
    {
       title: 'LEFT DOUBLE ARROW-TAIL',
       name1: 'UNICODE', code1: 'U+0291B',
       name2: 'HEX CODE', code2: '&#x291B;',
       name3: 'HTML CODE', code3: '&#10523;', h1: '&#10523;',
       name4: 'HTML ENTITY', code4: '&lAtail;',
    },
    {
       title: 'RIGHT DOUBLE ARROW-TAIL',
       name1: 'UNICODE', code1: 'U+0291C',
       name2: 'HEX CODE', code2: '&#x291C;',
       name3: 'HTML CODE', code3: '&#10524;', h1: '&#10524;',
       name4: 'HTML ENTITY', code4: '&rAtail;',
    },
    {
       title: 'LEFT ARROW TO BLACK DIAMOND',
       name1: 'UNICODE', code1: 'U+0291D',
       name2: 'HEX CODE', code2: '&#x291D;',
       name3: 'HTML CODE', code3: '&#10525;', h1: '&#10525;',
       name4: 'HTML ENTITY', code4: '&larrfs;',
    },
    {
       title: 'RIGHT ARROW TO BLACK DIAMOND',
       name1: 'UNICODE', code1: 'U+0291E',
       name2: 'HEX CODE', code2: '&#x291E;',
       name3: 'HTML CODE', code3: '&#10526;', h1: '&#10526;',
       name4: 'HTML ENTITY', code4: '&rarrfs;',
    },
    {
       title: 'LEFT ARROW FROM BAR TO BLACK DIAMOND',
       name1: 'UNICODE', code1: 'U+0291F',
       name2: 'HEX CODE', code2: '&#x291F;',
       name3: 'HTML CODE', code3: '&#10527;', h1: '&#10527;',
       name4: 'HTML ENTITY', code4: '&larrbfs;',
    },
    {
       title: 'RIGHT ARROW FROM BAR TO BLACK DIAMOND',
       name1: 'UNICODE', code1: 'U+02920',
       name2: 'HEX CODE', code2: '&#x2920;',
       name3: 'HTML CODE', code3: '&#10528;', h1: '&#10528;',
       name4: 'HTML ENTITY', code4: '&rarrbfs;',
    },
    {
       title: 'NORTH WEST AND SOUTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02921',
       name2: 'HEX CODE', code2: '&#x2921;',
       name3: 'HTML CODE', code3: '&#10529;', h1: '&#10529;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'NORTH EAST AND SOUTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+02922',
       name2: 'HEX CODE', code2: '&#x2922;',
       name3: 'HTML CODE', code3: '&#10530;', h1: '&#10530;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'NORTH WEST ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+02923',
       name2: 'HEX CODE', code2: '&#x2923;',
       name3: 'HTML CODE', code3: '&#10531;', h1: '&#10531;',
       name4: 'HTML ENTITY', code4: '&nwarhk;',
    },
    {
       title: 'NORTH EAST ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+02924',
       name2: 'HEX CODE', code2: '&#x2924;',
       name3: 'HTML CODE', code3: '&#10532;', h1: '&#10532;',
       name4: 'HTML ENTITY', code4: '&nearhk;',
    },
    {
       title: 'SOUTH EAST ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+02925',
       name2: 'HEX CODE', code2: '&#x2925;',
       name3: 'HTML CODE', code3: '&#10533;', h1: '&#10533;',
       name4: 'HTML ENTITY', code4: '&searhk;',
    },
    {
       title: 'SOUTH WEST ARROW WITH HOOK',
       name1: 'UNICODE', code1: 'U+02926',
       name2: 'HEX CODE', code2: '&#x2926;',
       name3: 'HTML CODE', code3: '&#10534;', h1: '&#10534;',
       name4: 'HTML ENTITY', code4: '&swarhk;',
    },
    {
       title: 'NORTH WEST ARROW AND NORTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02927',
       name2: 'HEX CODE', code2: '&#x2927;',
       name3: 'HTML CODE', code3: '&#10535;', h1: '&#10535;',
       name4: 'HTML ENTITY', code4: '&nwnear;',
    },
    {
       title: 'NORTH EAST ARROW AND SOUTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02928',
       name2: 'HEX CODE', code2: '&#x2928;',
       name3: 'HTML CODE', code3: '&#10536;', h1: '&#10536;',
       name4: 'HTML ENTITY', code4: '&nesear;',
    },
    {
       title: 'SOUTH EAST ARROW AND SOUTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+02929',
       name2: 'HEX CODE', code2: '&#x2929;',
       name3: 'HTML CODE', code3: '&#10537;', h1: '&#10537;',
       name4: 'HTML ENTITY', code4: '&seswar;',
    },
    {
       title: 'SOUTH WEST ARROW AND NORTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+0292A',
       name2: 'HEX CODE', code2: '&#x292A;',
       name3: 'HTML CODE', code3: '&#10538;', h1: '&#10538;',
       name4: 'HTML ENTITY', code4: '&swnwar;',
    },
    {
       title: 'RISING DIAGONAL CROSSING FALLING DIAGONAL',
       name1: 'UNICODE', code1: 'U+0292B',
       name2: 'HEX CODE', code2: '&#x292B;',
       name3: 'HTML CODE', code3: '&#10539;', h1: '&#10539;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'FALLING DIAGONAL CROSSING RISING DIAGONAL',
       name1: 'UNICODE', code1: 'U+0292C',
       name2: 'HEX CODE', code2: '&#x292C;',
       name3: 'HTML CODE', code3: '&#10540;', h1: '&#10540;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'SOUTH EAST ARROW CROSSING NORTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+0292D',
       name2: 'HEX CODE', code2: '&#x292D;',
       name3: 'HTML CODE', code3: '&#10541;', h1: '&#10541;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'NORTH EAST ARROW CROSSING SOUTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+0292E',
       name2: 'HEX CODE', code2: '&#x292E;',
       name3: 'HTML CODE', code3: '&#10542;', h1: '&#10542;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'FALLING DIAGONAL CROSSING NORTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+0292F',
       name2: 'HEX CODE', code2: '&#x292F;',
       name3: 'HTML CODE', code3: '&#10543;', h1: '&#10543;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'RISING DIAGONAL CROSSING SOUTH EAST ARROW',
       name1: 'UNICODE', code1: 'U+02930',
       name2: 'HEX CODE', code2: '&#x2930;',
       name3: 'HTML CODE', code3: '&#10544;', h1: '&#10544;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'NORTH EAST ARROW CROSSING NORTH WEST ARROW',
       name1: 'UNICODE', code1: 'U+02931',
       name2: 'HEX CODE', code2: '&#x2931;',
       name3: 'HTML CODE', code3: '&#10545;', h1: '&#10545;',
       name4: 'HTML ENTITY', code4: '',
    },
    {
       title: 'WAVE ARROW POINTING DIRECTLY RIGHT',
       name1: 'UNICODE', code1: 'U+02933',
       name2: 'HEX CODE', code2: '&#x2933;',
       name3: 'HTML CODE', code3: '&#10547;', h1: '&#10547;',
       name4: 'HTML ENTITY', code4: '&rarrc;',
    },
   //  {
   //     title: '',
   //     name1: 'UNICODE', code1: '',
   //     name2: 'HEX CODE', code2: '',
   //     name3: 'HTML CODE', code3: '', h1: '',
   //     name4: 'HTML ENTITY', code4: '',
   //  },
]

const bodyContainer = document.querySelector('.body-container');

const render = () => {

    ent.filter(data => {
        let div = document.createElement('div');
        div.classList = 'boxes';

        let h1 = document.createElement('h1');
        h1.innerHTML = `${data.h1}`;

        let h5 = document.createElement('h5');
        h5.innerText = `${data.title}`;
        h5.classList = 'title';
//------------------------------------------------------------------------->
        let h5CodeName = document.createElement('h5');
        h5CodeName.innerText = `${data.name1}`;
        h5CodeName.classList = 'codeName';

        let code1 = document.createElement('h5');
        code1.innerText = `${data.code1}`;
        code1.classList = 'code';
//------------------------------------------------------------------------->
        let h5CodeName1 = document.createElement('h5');
        h5CodeName1.innerText = `${data.name2}`;
        h5CodeName1.classList = 'codeName';

        let code2 = document.createElement('h5');
        code2.innerText = `${data.code2}`;
        code2.classList = 'code';
//------------------------------------------------------------------------->
        let h5CodeName2 = document.createElement('h5');
        h5CodeName2.innerText = `${data.name3}`;
        h5CodeName2.classList = 'codeName';

        let code3 = document.createElement('h5');
        code3.innerText = `${data.code3}`;
        code3.classList = 'code';
//------------------------------------------------------------------------->
        let h5CodeName3 = document.createElement('h5');
        h5CodeName3.innerText = `${data.name4}`;
        h5CodeName3.classList = 'codeName';

        let code4 = document.createElement('h5');
        code4.innerText = `${data.code4}`;
        code4.classList = 'code';
//------------------------------------------------------------------------->

        let div1 = document.createElement('div');
        div1.id = 'div-1';
        div1.appendChild(h5CodeName);
        div1.appendChild(code1);
        
        let div2 = document.createElement('div');
        div2.id = 'div-2';
        div2.appendChild(h5CodeName1);
        div2.appendChild(code2);

        let div3 = document.createElement('div');
        div3.id = 'div-3';
        div3.appendChild(h5CodeName2);
        div3.appendChild(code3);

        let div4 = document.createElement('div');
        div4.id = 'div-4';
        div4.appendChild(h5CodeName3);
        div4.appendChild(code4);

        div.appendChild(h1)
        div.appendChild(h5);
        div.appendChild(div1);
        div.appendChild(div2);
        div.appendChild(div3);
        div.appendChild(div4);
        bodyContainer.appendChild(div);
    })
   
}

render()